action_id: trunk-cache-prune
date: 2023-11-19 17:05:42
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1700413542
full_timestamp:
  nanos: 68938000
  seconds: 1700413542
trunk_version: 1.17.2
