action_id: trunk-upgrade-available
date: 2023-11-19 20:57:49
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1700427469
full_timestamp:
  nanos: 981465000
  seconds: 1700427469
trunk_version: 1.17.2
