action_id: trunk-upgrade-available
date: 2023-11-19 14:58:09
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1700405889
full_timestamp:
  nanos: 9315000
  seconds: 1700405889
trunk_version: 1.17.2
